version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  user_and_teams_service:
    build:
      context: services/user_and_teams_service
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./services/user_and_teams_service:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    labels:
      - "traefik.http.routers.user_and_teams_service.rule=Host(`user_and_teams_service.localhost`)"
      - "traefik.http.services.user_and_teams_service.loadbalancer.server.port=8888"